name: Buildroot Builder

on:
  workflow_dispatch:

env:
  WorkSpace: ~/Px30_Linux

jobs:
  build-Buildroot:
    runs-on: ubuntu-18.04

    steps:
      - name: "Cleanup Environment"
        uses: rokibhasansagar/slimhub_actions@main

      - name: Initializing environment
        run: |
          sudo -E apt-get clean
          sudo -E apt-get -qq update
          sudo -E apt-get install -qq aptitude
          sudo -E aptitude install -y build-essential crossbuild-essential-arm64 bash-completion vim locales time rsync bc python python3
          sudo -E aptitude install -y git ssh libssl-dev liblz4-tool lib32stdc++6 expect patchelf chrpath gawk texinfo diffstat binfmt-support qemu-user-static live-build bison flex fakeroot cmake unzip device-tree-compiler python-pip python3-pip ncurses-dev python-pyelftools python3-pyelftools subversion asciidoc w3m dblatex graphviz python-matplotlib python3-matplotlib cpio libparse-yapp-perl default-jre patchutils swig expect-dev u-boot-tools
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          git config --global user.name RC1844
          git config --global user.email "1844766234@qq.com"

      - name: Sync source
        run: |
          mkdir ${{env.WorkSpace}}
          cd ${{env.WorkSpace}}
          echo "::group::Repo Init"
          python3 ~/bin/repo init --depth=1 -u https://gitlab.com/firefly-linux/manifests.git -b master -m px30_linux_release.xml
          echo "::endgroup::"
          echo "::group::Repo Sync"
          python3 ~/bin/repo sync -c --no-tags
          python3 ~/bin/repo start firefly --all
          ./build.sh px30-lvds-buildroot.mk
          echo "::endgroup::"

      - name: Build Uboot
        run: |
          cd ${{env.WorkSpace}}
          ./build.sh uboot

      - name: Build Kernel
        run: |
          cd ${{env.WorkSpace}}
          ./build.sh kernel

      # - name: Build Recovery
      #   run: |
      #     cd ${{env.WorkSpace}}
      #     ./build.sh recovery

      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Build Buildroot
        run: |
          cd ${{env.WorkSpace}}
          ./build.sh buildroot

      - name: Make Firmware
        run: |
          cd ${{env.WorkSpace}}
          ./mkfirmware.sh

      - name: Make Pack
        run: |
          cd ${{env.WorkSpace}}
          ./build.sh updateimg

      - name: Upload Release
        uses: softprops/action-gh-release@master
        with:
          prerelease: true
          files: |
            ${{env.WorkSpace}}/rockdev/*
          name: Buildroot_${{github.run_id}}
          body: Buildroot
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
